export const CSS = [
  ".wsc-chip{display:inline-flex;align-items:center;gap:4px;min-width:0;max-width:220px;height:28px;padding:0 4px 0 8px;border:none;border-radius:24px;outline:none;background:transparent;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:20px;font-weight:500;font-family:inherit;cursor:pointer}",
  ".wsc-chip:hover{background:var(--dsw-alias-interactive-bg-hover)}",
  ".wsc-chip:focus-visible{box-shadow:0 0 0 2px var(--dsw-alias-border-l3)}",
  ".wsc-chip .wsc-chevron{flex:none;color:var(--dsw-alias-label-caption)}",
  ".wsc-seat-icon{flex:none;color:var(--dsw-alias-label-primary)}",
  ".wsc-overlay{position:fixed;inset:0;z-index:1000;display:flex;align-items:center;justify-content:center;pointer-events:none}",
  ".wsc-mask{position:absolute;inset:0;background:var(--dsw-alias-bg-mask-1);backdrop-filter:var(--dsw-mask-blur);pointer-events:auto}",
  ".wsc-panel{position:relative;z-index:1;display:flex;flex-direction:column;width:min(760px,calc(100vw - 48px));height:min(680px,calc(100vh - 48px));max-width:calc(100vw - 48px);border-radius:24px;overflow:hidden;background:var(--dsw-alias-bg-layer-2);box-shadow:var(--dsw-shadow-lv3);pointer-events:auto;color:var(--dsw-alias-label-primary)}",
  ".wsc-panel-head{flex:none;display:flex;align-items:center;justify-content:space-between;gap:8px;height:54px;padding:8px 14px 8px 24px;box-sizing:border-box}",
  ".wsc-panel-title{font-size:16px;line-height:24px;font-weight:500;color:var(--dsw-alias-label-primary)}",
  ".wsc-close{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;padding:0;border:none;border-radius:28px;background:transparent;cursor:pointer;color:var(--dsw-alias-label-primary)}",
  ".wsc-close:hover{background:var(--dsw-alias-interactive-bg-hover)}",
  ".wsc-panel-body{flex:1;min-height:0;padding:4px 24px 24px;overflow-y:auto;font-size:13px}",
  ".wsc-body{display:flex;flex-direction:column;gap:14px;width:100%;max-width:760px;color:var(--dsw-alias-label-primary)}",
  ".wsc-desc{color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.6;margin:0}",
  ".wsc-search{position:relative;display:flex;align-items:center;width:100%;color:var(--dsw-alias-label-tertiary)}",
  ".wsc-search > svg{position:absolute;left:12px;pointer-events:none}",
  ".wsc-search input{width:100%;height:36px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:0 34px 0 36px;outline:none;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit;font-size:13px;box-sizing:border-box}",
  ".wsc-search input::placeholder{color:var(--dsw-alias-label-tertiary)}",
  ".wsc-search input:focus-visible{border-color:var(--dsw-alias-state-business-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-state-business-primary) 18%,transparent)}",
  ".wsc-heading{display:flex;align-items:center;gap:7px;width:100%;padding:4px 2px;margin:0;border:0;border-radius:6px;background:transparent;color:inherit;font:inherit;text-align:left;cursor:pointer}",
  ".wsc-heading:hover{background:var(--dsw-alias-interactive-bg-hover)}",
  ".wsc-heading:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:1px}",
  ".wsc-heading h3{font-size:13px;line-height:20px;font-weight:600;margin:0}",
  ".wsc-heading span{font-size:12px;line-height:18px;color:var(--dsw-alias-label-tertiary);font-variant-numeric:tabular-nums}",
  ".wsc-heading-chevron{margin-left:auto;flex:none;color:var(--dsw-alias-label-tertiary)}",
  ".wsc-heading[data-collapsed='true'] .wsc-heading-chevron{transform:rotate(-90deg)}",
  ".wsc-cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));align-items:start;gap:10px;margin:0;padding:0;list-style:none}",
  ".wsc-card{min-width:0;overflow:hidden;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-layer-3)}",
  ".wsc-card[data-open='true']{border-color:var(--dsw-alias-border-l1);box-shadow:var(--dsw-shadow-lv1)}",
  ".wsc-card-main{box-sizing:border-box;display:flex;align-items:center;gap:10px;width:100%;min-height:52px;padding:12px 14px}",
  ".wsc-row{flex:1;min-width:0;display:flex;align-items:center;gap:7px;border:0;padding:0;background:transparent;color:inherit;font:inherit;text-align:left;cursor:pointer}",
  ".wsc-row:hover,.wsc-card[data-open='true'] .wsc-row{background:var(--dsw-alias-interactive-bg-hover)}",
  ".wsc-row:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:-2px}",
  ".wsc-card-title{flex:1;min-width:0;overflow:hidden;font-size:14px;line-height:20px;font-weight:600;text-overflow:ellipsis;white-space:nowrap}",
  ".wsc-tag{display:inline-flex;flex:none;align-items:center;min-height:20px;border-radius:5px;padding:1px 6px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);font-size:11px;line-height:16px;white-space:nowrap}",
  '.wsc-tag[data-enabled="true"]{background:color-mix(in srgb,var(--dsw-alias-state-success-primary) 10%,transparent);color:var(--dsw-alias-state-success-primary)}',
  ".wsc-chevron{flex:none;color:var(--dsw-alias-label-tertiary)}",
  ".wsc-card[data-open='true'] .wsc-chevron{transform:rotate(180deg)}",
  ".wsc-card-details{border-top:1px solid var(--dsw-alias-border-l2);padding:10px 14px 12px;background:var(--dsw-alias-bg-module-platform)}",
  ".wsc-detail-desc{margin:0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px;overflow-wrap:anywhere}",
  ".wsc-details{display:grid;grid-template-columns:76px minmax(0,1fr);gap:6px 10px;margin:8px 0 0}",
  ".wsc-details div{display:contents}",
  ".wsc-details dt{color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:17px}",
  ".wsc-details dd{min-width:0;margin:0;overflow-wrap:anywhere;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:17px}",
  ".wsc-switch{display:inline-flex;flex:none;align-items:center;padding:0;border:0;background:transparent;cursor:pointer;border-radius:999px}",
  ".wsc-switch:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}",
  ".wsc-switch-track{position:relative;display:inline-block;width:28px;height:16px;border-radius:999px;background:var(--dsw-alias-border-l2);transition:background-color 120ms var(--ds-ease-in-out)}",
  ".wsc-switch-track[data-on='true']{background:var(--dsw-alias-state-business-primary)}",
  ".wsc-switch-thumb{position:absolute;top:2px;left:2px;width:12px;height:12px;border-radius:50%;background:var(--dsw-alias-bg-layer-1);transition:transform 120ms var(--ds-ease-in-out)}",
  ".wsc-switch-track[data-on='true'] .wsc-switch-thumb{transform:translateX(12px)}",
  "@media (prefers-reduced-motion: no-preference){.wsc-chevron,.wsc-heading-chevron{transition:transform 140ms var(--ds-ease-in-out)}}",
  ".wsc-actions{display:flex;gap:8px;align-items:center;margin-top:4px}",
  ".wsc-btn{font-size:13px;line-height:22px;padding:4px 12px;border-radius:8px;border:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-1);color:inherit;cursor:pointer;font-family:inherit}",
  ".wsc-btn:hover{border-color:var(--dsw-alias-border-l2)}",
  ".wsc-btn:disabled{opacity:.6;cursor:default}",
  ".wsc-save{border-color:var(--dsw-alias-brand-primary)}",
  ".wsc-notice{font-size:12px;color:var(--dsw-alias-state-success-primary);margin:0}",
  ".wsc-error{font-size:12px;color:var(--dsw-alias-state-error-primary);margin:0}",
  ".wsc-hint{font-size:12px;color:var(--dsw-alias-label-secondary);line-height:1.6;margin:0}",
  "@media (max-width: 680px){.wsc-cards{grid-template-columns:minmax(0,1fr)}}",
].join("\n");
